config/routes.rb
RentifyWeb::Application.routes.draw do

  resources :contacts, :only => [:new, :create]
  resources :photos,   :only => [:index]

  get "info/terms"
  get "info/site_not_found"

  get "availabilities/index"
  get "directions/index"
  get "descriptions/index"
  get "home/index"

  root :to => 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :country, :lat, :lng, :post_code, :state, :user_set_lat, :user_set_lng

  validates :address,   presence: true
  validates :city,      presence: true
  validates :country,   presence: true
  validates :post_code, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :description, :group, :source_id, :source_type, :title
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  attr_accessible :enabled, :path, :provider, :property_id

  belongs_to :property
end

app/models/contact_us.rb
class ContactUs < MailForm::Base
  attribute :name,    validate: true, message: 'The Name can\'t be blank.'
  attribute :email,   validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i,
                      message: 'The Email Address you entered does not appear to be valid.'
  attribute :subject, validate: true, message: 'The Subject can\'t be blank.'
  attribute :message, validate: true, message: 'The Message can\'t be blank.'
  attribute :send_to

  # Declare the e-mail headers. It accepts anything the mail method in ActionMailer accepts.
  def headers
    {
      subject: subject,
      to:      send_to,
      from:    %("#{name}" <#{email}>)
    }
  end
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  attr_accessible :description, :property_id, :title

  has_one :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :description, :address, :title, :user, :user_id, :address_id

  belongs_to :user
  belongs_to :address

  has_many   :directions
  has_many   :photos, class_name: 'PropertyPhoto'
  has_many   :calendars
  has_many   :articles, conditions: { source_type: 'property' },
                        foreign_key: 'source_id',
                        dependent: :destroy

  accepts_nested_attributes_for :address

  validates :user,        presence: true
  validates :address,     presence: true
  validates :title,       presence: true
  validates :description, presence: true
end

app/models/property_photo.rb
class PropertyPhoto < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  attr_accessible :image, :property

  belongs_to :property

  mount_uploader :image, PhotoUploader

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :domain, :subdomain, :style, :title, :address, :user, :email, :phone

  belongs_to  :address
  belongs_to  :user

  validates :user,      presence: true
  validates :phone,     presence: true
  validates :email,     presence: true,
                        format:   { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :style,     presence: true
  validates :subdomain, presence: true,
                        uniqueness: true
  validates :domain,    uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :password

  has_many :properties
  has_many :sites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from SiteNotFound, with: :site_not_found_error

  helper_method :current_site

  before_filter :load_property

  layout :set_layout

  def site_not_found_error
    redirect_to info_site_not_found_path
  end

protected

  def current_site
    @current_site ||= begin
      if request.domain == configatron.domain
        site = Site.where(subdomain: request.subdomain).first
      else
        site = Site.where(domain: "#{request.subdomain}.#{request.domain}").first
      end
      raise SiteNotFound unless site

      site
    end
  end

private

  def load_property
    @property = current_site.user.properties.first.decorate
  end

  def set_layout
    if request.xhr? 
      false
    else
      current_site.style || 'style_01'
    end
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  def index
    @calendar = @property.calendars.where(provider: 'google').first
    @articles = @property.articles.where(group: 'availability').decorate
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts/new
  def new
    @contact = ContactUs.new
  end

  # POST /contacts
  def create
    @contact = ContactUs.new(params[:contact_us].merge(send_to: current_site.email))

    if @contact.valid?
      @contact.deliver
      redirect_to new_contact_path, notice: 'Thank you for your message, we will contact you shortly!'
    else
      render action: "new"
    end
  end

end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index
  end
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def site_not_found
    render layout: 'application'
  end

  def terms
    @articles = @property.articles.where(group: 'terms').decorate
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/views/availabilities/index.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: @property.title } %>
<% end %>
<!-- Start availabilities -->
<section class="availabilities" id='content'>
  <div class="container">  
    <hr class="divider-home">              
    <div class="row">
      <div class="span3">
        <div class="section-overview">
          <h5><span><i class="icon-minus"></i></span> Availability</h5>  
          <hr>
          <%= render 'shared/left_nav' %>
        </div>
      </div>
      <div class="span9">
        <% @articles.each do | article | %>
          <h3><%= article.title %></h3>
          <%= article.description_to_html.html_safe %>
        <% end %>
        <hr>
        <div id='calendar' data-path='<%= @calendar.path %>'></div>
      </div>
    </div>
  </div>
</section>
<!-- End availabilities -->

app/views/contacts/new.html.erb
<%= render partial: 'shared/welcome_message', locals: { message: '- Contact Us -' } %>
<!-- Start contact -->
<section class="contact">
  <div class="container">
    <div class="row">
      <div class="span4 our-office">
        <h4>CONTACT DETAILS</h4>
        <hr>
        <dl>
          <% if current_site.address %>
            <dt>Our Location:</dt>
            <dd>
              <%= current_site.address.address %><%= ", #{current_site.address.address2}" if current_site.address.address2 %><br>
              <%= current_site.address.city %>, <%= current_site.address.state %>, <%= current_site.address.post_code %><br>
              <%= current_site.address.country %>
            </dd>
          <% end %>
          <% if current_site.phone %>
            <dt>Telephone:</dt>
            <dd>
              <%= current_site.phone %>
            </dd>
          <% end %>
          <% if current_site.email %>
            <dt>E-mail:</dt>
            <dd><a href="mailto:<%= current_site.email %>"><%= current_site.email %></a></dd>
          <% end %>
        </dl>
      </div>
      <div class="span8 contact-form">
        <h4>SEND US A MESSAGE</h4>
        <hr>
        <%= form_for(@contact, url: contacts_path, html: {:name => 'contactform'}) do |f| %>
          <% if @contact.errors.any? %>
            <div class="error" style='color:#a00;'>
              We are very sorry, but there were error(s) found with the form you submitted.<br/>
              These errors appear below.<br /><br />
              <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="span4">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'span4' %>
            </div>
            <div class="span4">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'span4' %>
            </div>
            <div class="span8">
              <%= f.label :subject %>
              <%= f.text_field :subject, class: 'span8' %>
            </div>
            <div class="span8">
              <%= f.label :message %><br />
              <%= f.text_area :message, class: 'span8', rows: '8' %>
            </div>  
            <div class="span8">
              <%= f.submit 'Submit message', class: 'btn btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- End contact -->

app/views/descriptions/index.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: '- Descriptions -' } %>
<% end %>
<!-- Start description -->
<section class="description" id='content'>
  <div class="container">  
    <hr class="divider-home">              
    <div class="row">
      <div class="span3">
        <div class="section-overview">
          <h5><span><i class="icon-minus"></i></span> Description</h5>  
          <hr>
          <%= render 'shared/left_nav' %>
        </div>
      </div>
      <div class="span9">
        <h3><%= @property.title %></h3>
        <%= @property.description_to_html.html_safe %>
      </div>
    </div>
  </div>
</section>
<!-- End description -->

app/views/directions/index.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: '- Directions -' } %>
<% end %>
<!-- Start directions -->
<section class="directions" id='content'>
  <div class="container">  
    <hr class="divider-home">              
    <div class="row">
      <div class="span3">
        <div class="section-overview">
          <h5><span><i class="icon-minus"></i></span> Directions</h5>  
          <hr>
          <%= render 'shared/left_nav' %>
        </div>
      </div>
      <div class="span9">
        <h3>How to find us</h3>
        <% @property.directions.decorate.each do | direction | %>
          <h3><%= direction.title %></h3>
          <%= direction.description_to_html.html_safe %>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- End directions -->

app/views/home/index.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: @property.title } %>
<% end %>
<!-- Start portfolio -->
<section class="portfolio">
  <div class="container">
    <div class="row">
      <div class="span8">
        <div class="img-polaroid portfolio-item">
          <%= image_tag @property.photos.first.image.url %>
          <div class="folio-body">
            <div class="folio-info">
              <h5><%= @property.title %></h5>
              <%= @property.description_to_html.html_safe %>
            </div>
            <div class="folio-zoom">
              <%= link_to 'Show all photos', photos_path %>
            </div>
          </div>
        </div>
      </div>
      <div class="span4">
        <div class="project-widget well info-box">
           <iframe marginheight="0" marginwidth="0" frameborder="0" height="490px" scrolling="no" width="330px"
                   src="http://maps.google.com/maps?oe=utf-8&amp;client=firefox-a&amp;q=uttara&amp;ie=UTF8&amp;hq=uttara&amp;hnear=&amp;t=m&amp;ll=37.262153,-79.942041&amp;spn=0.006295,0.006295&amp;output=embed"></iframe>
        </div>
      </div>
      <div class='span12'>
        <h4>Description</h4>
        <hr>
        <%= @property.description_to_html.html_safe %>
      </div>
    </div>
  </div>
</section>
<!-- End portfolio -->
<!-- Start page header -->
<section class="section-page-header">
  <div class="container">
    <img src="/assets/divider_shadow.png" title="" alt="">
  </div>
</section>
<!-- End page header -->
<!-- Start services -->
<section class="services" id='content'>
  <div class="container">
    <div class="row">
      <div class="span3">
        <div class="well well-small">
          <span class="service-icon"><i class="icon-resize-full"></i></span>
          <h5>Photos</h5>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam vehicula ut id elit.</p>
          <%= link_to "Read More", photos_path, class: 'btn btn-mini' %>
        </div>
      </div>
      <div class="span3">
        <div class="well well-small">
          <span class="service-icon"><i class="icon-list"></i></span>
          <h5>Directions</h5>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam vehicula ut id elit.</p>
          <%= link_to "Read More", directions_index_path, data: { remote: true, update: 'content'}, class: 'btn btn-mini' %>
        </div>
      </div>
      <div class="span3">
        <div class="well well-small">
          <span class="service-icon"><i class="icon-th"></i></span>
          <h5>Availability</h5>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam vehicula ut id elit.</p>
          <%= link_to "Read More", availabilities_index_path, data: { remote: true, update: 'content'}, class: 'btn btn-mini' %>
        </div>
      </div>
      <div class="span3">
        <div class="well well-small">
          <span class="service-icon"><i class="icon-ok"></i></span>
          <h5>Contact Us</h5>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam vehicula ut id elit.</p>
          <%= link_to "Read More", new_contact_path, class: 'btn btn-mini' %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End services -->

app/views/info/site_not_found.html.erb
<%= render partial: 'shared/welcome_message', locals: { message: '- Not found type of text -' } %>
<!-- Start no-site-found -->                                               
<section class="http-404">
  <div class="container">
    <div class="row">
      <div class="span12 http-404">
        <h1>404</h1>                        
        <h3>Sorry, this web page is no longer available!</h3>
      </div>
    </div>
  </div>
</section>     
<!-- End no-site-found -->   

app/views/info/terms.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: '- Terms and Conditions -' } %>
<% end %>
<!-- Start terms -->
<section class="terms" id='content'>
  <div class="container">  
    <hr class="divider-home">              
    <div class="row">
      <div class="span3">
        <div class="section-overview">
          <h5><span><i class="icon-minus"></i></span> Terms</h5>  
          <hr>
          <%= render 'shared/left_nav' %>
        </div>
      </div>
      <div class="span9">
        <% @articles.each do | article | %>
          <h3><%= article.title %></h3>
          <%= article.description_to_html.html_safe %>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!-- End terms -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentifyWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/style_01.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Basic Needs -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= current_site.title %></title>
    <!-- Fonts -->
    <link href = 'http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,800' rel = 'stylesheet' type = 'text/css'>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Favicon Icon -->
    <link rel="shortcut icon" href="/assets/ico/favicon.png">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= bootstrap_flash %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/socked' %>
  </body>
</html>

app/views/photos/index.html.erb
<% unless request.xhr? %>
  <%= render partial: 'shared/welcome_message', locals: { message: '- Photos -' } %>
<% end %>

<!-- Start portfolio -->
<section class="portfolio">
  <div class="container">
    <div class="row">
      <div class="span12">
        <ul class="thumbnails">
          <% @property.photos.each do | photo | %>
            <li class="span2">
              <div class="thumbnail">
                <div class="portfolio-item">
                  <%= image_tag photo.image.thumb.url %>
                  <div class="folio-body">
                    <div class="folio-info">
                    </div>
                    <div class="folio-zoom">
                      <%= link_to photo.image.url, rel: 'prettyPhoto[pp_gal]' do %>
                        <i class="icon-plus"></i> Zoom
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
        <hr>
      </div>
    </div>
  </div>
</section>
<!-- End portfolio -->

app/views/shared/_footer.html.erb
<!-- Start footer -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="span3 about">
        <h5>About Us</h5>
        <p>Lorem ipsum dolor sit amet nec, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.</p>
        <dl>
          <dt>Our Office:</dt>
          <dd>
            <strong>Rounde Inc.</strong><br>
            795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107
          </dd>
          <dt>Telephone:</dt>
          <dd>
            +1 0198 432 4567<br>
            +1 0198 432 4567
          </dd>
          <dt>E-mail:</dt>
          <dd><a href="mailto:mail@domain.com">mail@domain.com</a></dd>
        </dl>
      </div>
      <div class="span3 recent-post">
        <h5>Recent Posts</h5>
        <ul>
          <li>
            <div class="row">
              <div class="span1">
                <a href="#"><img src="/assets/round/magic-landscape.jpg" alt="" /></a>
              </div>
              <div class="recent-body">
                <a href="#">Erat nisl faucibus justo verit et quasi architecto beatae.</a><br>
                <em><small>January 11, 2012 - 1:13 PM</small></em>
              </div>
            </div>
          </li>
          <li>
            <div class="row">
              <div class="span1">
                <a href="#"><img src="/assets/round/shopping-high-heels.jpg" alt=""></a>
              </div>
              <div class="recent-body">
                <a href="#">Ut semper porttitor ipsum, et cursus erat volutpat vitae.</a><br>
                <em><small>January 12, 2012 - 1:13 PM</small></em>
              </div>
            </div>
          </li>
          <li>
            <div class="row">
              <div class="span1">
                <a href="#"><img src="/assets/round/nettle-tea.jpg" alt="" /></a>
              </div>
              <div class="recent-body">
                <a href="#">Mauris porttitor nisi sit amet felis porta congue.</a><br>
                <em><small>January 13, 2012 - 1:13 PM</small></em>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="span3 twitter-widget">
        <h5>Latest Tweets</h5>
        <div class="tweet"></div>
      </div>
      <div class="span3 flickr-widget">
        <h5>Flickr Photos</h5>
        <ul class="flickr thumbnails"></ul>
      </div>
    </div>
  </div>
</footer>
<!-- End footer -->

app/views/shared/_header.html.erb
<!-- Start header -->
<header class="header">
  <div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="brand-wrapper">
          <a class="brand" href="<%= url_for root_path %>"><i class="icon-check-empty"></i> ROUN<span>DE</span></a>
        </div>
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
<!--
          <li class="<%= "active" if controller.controller_name == "descriptions"%>">
            <%= link_to "Description", descriptions_index_path %>
          </li>
-->
          <li class="<%= "active" if controller.controller_name == "photos"%>">
            <%= link_to "Photos", photos_path %>
          </li>
          <li class="<%= "active" if controller.controller_name == "directions"%>">
            <%= link_to "Directions", directions_index_path %>
          </li>
          <li class="<%= "active" if controller.controller_name == "availabilities"%>">
            <%= link_to "Availability", availabilities_index_path %>
          </li>
          <li class="<%= "active" if controller.controller_name == "info" && controller.action_name == "terms" %>">
            <%= link_to "Terms", info_terms_path %>
          </li>
          <li class="<%= "active" if controller.controller_name == "contacts" %>">
            <%= link_to "Contact Us", new_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>
<!-- End header --> 

app/views/shared/_left_nav.html.erb
<% options = { data: { remote: true, update: 'content'} } %>

<ul class="nav nav-list">
  <li><%= link_to "Home", root_path, options %></li>
<!--
  <li class="<%= "active" if controller.controller_name == "descriptions"%>">
     <%= link_to "Description", descriptions_index_path, options %>
  </li>
-->
  <li class="<%= "active" if controller.controller_name == "photos"%>">
     <%= link_to "Photos", photos_path %>
  </li>
  <li class="<%= "active" if controller.controller_name == "directions"%>">
    <%= link_to "Directions", directions_index_path, options %>
  </li>
  <li class="<%= "active" if controller.controller_name == "availabilities"%>">
    <%= link_to "Availability", availabilities_index_path, options %>
  </li>
  <li class="<%= "active" if controller.controller_name == "info" && controller.action_name == "terms" %>">
    <%= link_to "Terms", info_terms_path, options %>
  </li>
  <li class="<%= "active" if controller.controller_name == "contacts" %>">
    <%= link_to "Contact Us", new_contact_path %>
  </li>
</ul>

app/views/shared/_slider.html.erb
<!-- Start slider -->
<section class="slider">
  <div class="container">
    <div class="well">
      <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="active item">
            <img src="/assets/slides/slide_1.jpg" />
            <div class="carousel-caption animation">
              <h3 data-animate="fadeInDownBig" class="caption-black">Living room</h3>
              <p data-animate="fadeInRightBig" class="caption-black-small">Some small living room description</p>
            </div>
          </div>
          <div class="item">
            <img src="/assets/slides/slide_2.jpg" />
            <div class="carousel-caption animation">
              <h3 data-animate="fadeInLeftBig" class="caption-black">Bedroom 1</h3>
              <p data-animate="fadeInRightBig" class="caption-black-small">Some small bedroom 1 description</p>
            </div>
          </div>
          <div class="item">
            <img src="/assets/slides/slide_3.jpg" />
            <div class="carousel-caption animation">
              <h3 data-animate="fadeInLeftBig" class="caption-black">Bedroom 2</h3>
              <p data-animate="fadeInRightBig" class="caption-black-small">Some small bedroom 1 description</p>
            </div>
          </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev"><i class="icon-chevron-left"></i></a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next"><i class="icon-chevron-right"></i></a>
      </div>
    </div>
  </div>
</section>
<!-- End slider -->

app/views/shared/_socked.html.erb
<!-- Start socket -->
<section class="socket">
  <div class="container">
    <div class="row">
      <div class="span6">
        <span>© 2013 Rentify Inc. All rights reserved.</span>     
      </div>
      <div class="span6">
        <ul class="social-links">
          <li>Stay Connected</li>
          <li><a href="#"><i class="icon-facebook"></i></a></li>
          <li><a href="#"><i class="icon-twitter"></i></a></li>
          <li><a href="#"><i class="icon-linkedin"></i></a></li>
          <li><a href="#"><i class="icon-pinterest"></i></a></li>
          <li><a href="#"><i class="icon-google-plus"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- End socket -->

app/views/shared/_welcome_message.html.erb
<!-- Start page header -->
<section class="section-page-header">
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="page-header">
          <h4><%= message %></h4>
        </div>
      </div>
    </div>
    <img src="/assets/divider_shadow.png" title="" alt="">
  </div>
</section>
<!-- End page header -->